### ISSUE TITLE
outside usage?

### ISSUE THREAD

**Issue by michapr** [Sensirion/embedded-sps#17]
Have you any recommendations for outside usage of your sensor?
Temperature range is nice, but what can happen if humidity is >95%? 
What is the best protection method?

Thanks,
Michael

**Comment by abrauchli** [comment]
Hi @michapr 

I don't feel too qualified to answer that as software dev, so I forwarded the question internally but it'll take a few days. Thanks for your patience.

**Comment by winkj** [comment]
@michapr apologies for the delay. 

For any product related questions - especially when it comes to design-in - it's best to reach out to Sensirion's product support team at https://www.sensirion.com/en/about-us/contact/. They will be the best to answer this request. 

I will close this issue, since it's not related to the software project. If you fail to get a response from our support team, please feel free to contact me through email (see commit logs)

**Comment by michapr** [comment]
"great" ... I'm still waiting for your answer:
You wrote:
"so I forwarded the question internally but it'll take a few days. Thanks for your patience."

So - if you didn't got any response until today, why you think that I will get any? :(

**Comment by winkj** [comment]
It's most likely that it got lost internally, since our support team focuses primarily on customer requests. Reaching out through the official channel will therefore be the best way to get this answered.
